Repository nipy/heudiconv, pull requests merged in 2023-05, with the labels that each got.

#673 Make an `embed_dicom_and_nifti_metadata()` annotation work on Python 3.7
  heudiconv/dicoms.py
Labels: patch

#671 Declare `custom_grouping` return type instead of casting
  heudiconv/dicoms.py
Labels: internal

#570 BF(?): make _setter images be taken as scouts - only DICOMs are saved
  heudiconv/heuristics/reproin.py
Labels: patch, release

#675 Make .subsecond optional in BIDS/DICOM datetime entries
  heudiconv/bids.py
  heudiconv/dicoms.py
  heudiconv/tests/test_utils.py
  heudiconv/utils.py
Labels: patch, release
