Repository nipy/heudiconv, pull requests merged in 2023-02, with the labels that each got.

#628 dcm2niix explicitly noted as a (PyPI) dependency and removed from being installed via apt-get etc
  .github/workflows/test.yml
  Dockerfile
  docs/installation.rst
  heudiconv/info.py
  utils/gen-docker-image.sh
Labels: internal

#645 Clarify the infotodict function
  docs/heuristics.rst
  docs/installation.rst
Labels: documentation

#615 Add a bash anon-cmd to be used to incrementally anonymize sids
  utils/anon-cmd
Labels: enhancement, documentation

#639 Reword number of intended ideas in README.rst
  README.rst
Labels: documentation

#635 Add 3.11 to be tested etc
  .github/workflows/test.yml
  heudiconv/info.py
Labels: tests

#647 strip non-alphanumeric from session ids too
  heudiconv/bids.py
  heudiconv/convert.py
  heudiconv/tests/test_bids.py
Labels: minor, release
