Repository nipy/heudiconv, pull requests merged in 2023-04, with the labels that each got.

#655 Remove use of `six`
  heudiconv/info.py
  heudiconv/tests/test_heuristics.py
  heudiconv/tests/test_main.py
  heudiconv/tests/test_tarballs.py
Labels: dependencies

#471 ENH: Support extracting DICOMs from ZIP files (and possibly other archives) by switching to use shutil.unpack_archive instead of tarfile module functionality
  heudiconv/parser.py
  heudiconv/tests/test_archives.py
Labels: minor

#658 Add & apply pre-commit and lint job
  .codespellrc
  .github/ISSUE_TEMPLATE.md
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  README.rst
  custom/dbic/singularity-env.def
  docs/Makefile
  docs/conf.py
  docs/installation.rst
  docs/tutorials.rst
  heudiconv/__init__.py
  heudiconv/bids.py
  heudiconv/cli/monitor.py
  heudiconv/cli/run.py
  heudiconv/convert.py
  heudiconv/dicoms.py
  heudiconv/due.py
  heudiconv/external/dcmstack.py
  heudiconv/external/dlad.py
  heudiconv/external/pydicom.py
  heudiconv/external/tests/test_dlad.py
  heudiconv/heuristics/banda-bids.py
  heudiconv/heuristics/bids_ME.py
  heudiconv/heuristics/bids_PhoenixReport.py
  heudiconv/heuristics/bids_with_ses.py
  heudiconv/heuristics/cmrr_heuristic.py
  heudiconv/heuristics/convertall.py
  heudiconv/heuristics/example.py
  heudiconv/heuristics/multires_7Tbold.py
  heudiconv/heuristics/reproin.py
  heudiconv/heuristics/reproin_validator.cfg
  heudiconv/heuristics/studyforrest_phase2.py
  heudiconv/heuristics/test_b0dwi_for_fmap.py
  heudiconv/heuristics/test_reproin.py
  heudiconv/heuristics/uc_bids.py
  heudiconv/info.py
  heudiconv/main.py
  heudiconv/parser.py
  heudiconv/queue.py
  heudiconv/tests/anonymize_script.py
  heudiconv/tests/conftest.py
  heudiconv/tests/test_archives.py
  heudiconv/tests/test_bids.py
  heudiconv/tests/test_convert.py
  heudiconv/tests/test_dicoms.py
  heudiconv/tests/test_heuristics.py
  heudiconv/tests/test_main.py
  heudiconv/tests/test_monitor.py
  heudiconv/tests/test_queue.py
  heudiconv/tests/test_regression.py
  heudiconv/tests/test_tarballs.py
  heudiconv/tests/test_utils.py
  heudiconv/tests/utils.py
  heudiconv/utils.py
  setup.py
  tox.ini
Labels: tests, internal

#666 Make `test_private_csa_header` test write to temp dir
  heudiconv/tests/test_dicoms.py
Labels: tests

#664 Write command arguments as lists of strings instead of splitting strings on whitespace
  heudiconv/cli/monitor.py
  heudiconv/tests/test_convert.py
  heudiconv/tests/test_heuristics.py
  heudiconv/tests/test_main.py
  heudiconv/tests/test_queue.py
Labels: internal

#662 Remove kludgy support for older versions of pydicom and dcmstack
  heudiconv/bids.py
  heudiconv/dicoms.py
  heudiconv/external/dcmstack.py
  heudiconv/external/pydicom.py
  heudiconv/heuristics/multires_7Tbold.py
  heudiconv/info.py
  heudiconv/tests/test_dicoms.py
  heudiconv/tests/test_regression.py
Labels: dependencies

#663 Add `sample_nifti.json` to `.gitignore`
  .gitignore
Labels: internal

#661 Replace third-party `mock` library with stdlib's `unittest.mock`
  heudiconv/dicoms.py
  heudiconv/heuristics/test_reproin.py
  heudiconv/info.py
  heudiconv/tests/test_heuristics.py
  heudiconv/tests/test_main.py
  heudiconv/tests/test_monitor.py
  heudiconv/tests/test_utils.py
Labels: dependencies

#659 Don't call `logging.basicConfig()` in `__init__.py`
  heudiconv/__init__.py
  heudiconv/cli/run.py
Labels: patch

#656 Add type annotations
  .github/workflows/typing.yml
  heudiconv/bids.py
  heudiconv/cli/monitor.py
  heudiconv/cli/run.py
  heudiconv/convert.py
  heudiconv/dicoms.py
  heudiconv/external/dlad.py
  heudiconv/external/tests/test_dlad.py
  heudiconv/heuristics/banda-bids.py
  heudiconv/heuristics/bids_ME.py
  heudiconv/heuristics/bids_PhoenixReport.py
  heudiconv/heuristics/bids_with_ses.py
  heudiconv/heuristics/cmrr_heuristic.py
  heudiconv/heuristics/convertall.py
  heudiconv/heuristics/example.py
  heudiconv/heuristics/multires_7Tbold.py
  heudiconv/heuristics/reproin.py
  heudiconv/heuristics/studyforrest_phase2.py
  heudiconv/heuristics/test_b0dwi_for_fmap.py
  heudiconv/heuristics/test_reproin.py
  heudiconv/heuristics/uc_bids.py
  heudiconv/info.py
  heudiconv/main.py
  heudiconv/parser.py
  heudiconv/py.typed
  heudiconv/queue.py
  heudiconv/tests/anonymize_script.py
  heudiconv/tests/conftest.py
  heudiconv/tests/test_archives.py
  heudiconv/tests/test_bids.py
  heudiconv/tests/test_convert.py
  heudiconv/tests/test_dicoms.py
  heudiconv/tests/test_heuristics.py
  heudiconv/tests/test_main.py
  heudiconv/tests/test_monitor.py
  heudiconv/tests/test_queue.py
  heudiconv/tests/test_regression.py
  heudiconv/tests/test_tarballs.py
  heudiconv/tests/test_utils.py
  heudiconv/tests/utils.py
  heudiconv/utils.py
  mypy.ini
  setup.py
  tox.ini
Labels: internal
