Repository nipy/heudiconv, pull requests merged in 2023-03, with the labels that each got.

#643 Reword and correct punctuation on installation.rst
  docs/installation.rst
Labels: documentation

#651 Re-add explicit instructions to install dcm2niix "manually" and remove it from install_requires
  .github/workflows/test.yml
  docs/installation.rst
  heudiconv/dicoms.py
  heudiconv/info.py
  utils/gen-docker-image.sh
Labels: patch, release

#652 [DATALAD RUNCMD] produce updated dockerfile
  Dockerfile
Labels: release, internal

#654 Replace py.path with pathlib
  heudiconv/cli/monitor.py
Labels: internal
