Repository nipy/heudiconv, pull requests merged in 2024-09, with the labels that each got.

#781 Run tests weekly to ensure we are still good
  .github/workflows/test.yml
Labels: tests

#782 Fixup testing: kludge for pydicom 3.0.0 in dcmstack, ignore some warnings from nipype for python 3.12
  heudiconv/dicoms.py
  tox.ini
Labels: patch, release

#784 Just INFO not WARNING if heuristic is missing intotoids
  heudiconv/parser.py
Labels: UX

#753 extract sequence_name from PulseSequenceName on Siemens XA** data
  heudiconv/dicoms.py
  heudiconv/tests/test_dicoms.py
Labels: patch
