Repository nipy/heudiconv, pull requests merged in 2024-05, with the labels that each got.

#756 Handle cases where dates/times in DICOM are empty strings, not Nones (e.g. after some anonymization)
  heudiconv/dicoms.py
Labels: patch, release

#757 Fix typo
  CONTRIBUTING.rst
Labels: skip-release

#747 Add Jpeg2000 to Docker container
  Dockerfile
  utils/gen-docker-image.sh
Labels: internal

#758 Add CITATION.cff based on JOSS paper.md
  .github/workflows/lint.yml
  CITATION.cff
Labels: release, internal

#759 Replace one rogue markdown [ref](url) to `ref <url>`_ RST
  docs/reproin.rst
Labels: documentation

#760 Specify license in CITATION.cff
  CITATION.cff
Labels: release, documentation

#762 Codespell tuneup: no dedicated workflow (part of tox -e lint), and fix few freshly detected typos
  .github/workflows/codespell.yml
  docs/installation.rst
  heudiconv/bids.py
Labels: internal
