Repository nipy/heudiconv, pull requests merged in 2024-10, with the labels that each got.

#780 timezone aware
  heudiconv/bids.py
  heudiconv/dicoms.py
  heudiconv/tests/test_utils.py
  heudiconv/utils.py
Labels: minor

#787 BF(workaround): if heuristic provided just a string and not list of types -- make it into a tuple
  heudiconv/convert.py
Labels: patch, release

#793 Fix assignment of sensitive git-annex metadata data via glob patterns (regression introduced by #739)
  heudiconv/external/dlad.py
  heudiconv/tests/test_regression.py
Labels: patch, release

#796 Do specify filter="tar" when extracting tars
  heudiconv/parser.py
Labels: patch

#790 Docker image: Use newer debian stable for the base and newer dcm2niix
  Dockerfile
  utils/gen-docker-image.sh
Labels: internal

#799 Add Python 3.12 into github testing CI
  .github/workflows/test.yml
Labels: tests
