Repository nipy/heudiconv, pull requests merged in 2024-02, with the labels that each got.

#728 properly remove GE multiecho bvals/bvecs
  heudiconv/convert.py
  heudiconv/tests/data/non_zeros.bval
  heudiconv/tests/data/zeros.bval
  heudiconv/tests/test_convert.py
Labels: patch

#741 Adjust wording on heuristics page -- do not claim creating some skeleton
  docs/heuristics.rst
  docs/tutorials.rst
Labels: release, documentation

#745 Fix - auto is in ~/, not in the PATH
  .github/workflows/release.yml
Labels: release, internal

#746 auto 11.0.5 is needed to avoid hitting some "Error: fatal: ... not an integer" bug
  .github/workflows/release.yml
Labels: release, internal

#581 Add support for a custom seqinfo to extract from DICOMs any additional metadata desired for a heuristic
  README.rst
  docs/heuristics.rst
  heudiconv/convert.py
  heudiconv/dicoms.py
  heudiconv/heuristics/convertall.py
  heudiconv/heuristics/convertall_custom.py
  heudiconv/parser.py
  heudiconv/tests/test_dicoms.py
  heudiconv/utils.py
Labels: minor, release
